"""Aggiunti nome, cognome e foto profilo al modello User

Revision ID: 492222dc99c5
Revises: 596337d57853
Create Date: 2025-02-25 01:43:34.157532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492222dc99c5'
down_revision = '596337d57853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cognome', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('profilo_foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profilo_foto')
        batch_op.drop_column('cognome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
