"""Aggiunti nuovi campi per Viewer con supporto a viste personalizzate

Revision ID: 5444b822351e
Revises: aa0d465df818
Create Date: 2025-02-25 01:55:52.904133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5444b822351e'
down_revision = 'aa0d465df818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('columns', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('filters', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sorting', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('modular_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'modulars', ['modular_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('user_id')
        batch_op.drop_column('modular_id')
        batch_op.drop_column('sorting')
        batch_op.drop_column('filters')
        batch_op.drop_column('columns')

    # ### end Alembic commands ###
