"""Aggiunta tenant_id al modello Kanban

Revision ID: 596337d57853
Revises: a8adb1cdf78c
Create Date: 2025-02-25 01:06:07.465457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596337d57853'
down_revision = 'a8adb1cdf78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kanbans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kanbans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
