"""Aggiunti nuovi campi per le modalità e collegamento con i tenants

Revision ID: 860fedbd208d
Revises: c0712f7827ee
Create Date: 2025-02-25 01:48:38.111325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860fedbd208d'
down_revision = 'c0712f7827ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('settings')
        batch_op.drop_column('description')
        batch_op.drop_column('mode_type')

    # ### end Alembic commands ###
