"""Aggiunti nuovi campi per Modular con supporto alla creazione autonoma

Revision ID: aa0d465df818
Revises: 860fedbd208d
Create Date: 2025-02-25 01:50:51.993559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0d465df818'
down_revision = '860fedbd208d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modular_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_template')
        batch_op.drop_column('is_active')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('config')
        batch_op.drop_column('modular_type')

    # ### end Alembic commands ###
