"""Aggiunti nuovi campi per l'editor e collegamento con i tenants

Revision ID: c0712f7827ee
Revises: 492222dc99c5
Create Date: 2025-02-25 01:46:52.767948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0712f7827ee'
down_revision = '492222dc99c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editor_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('config_options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('is_active')
        batch_op.drop_column('config_options')
        batch_op.drop_column('editor_type')

    # ### end Alembic commands ###
